name: Test Github Environments
on:
  push:

jobs:
  SetEnvironment:
    name: Set Environment
    runs-on: ubuntu-latest
    steps:
      - name: Check Prod
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "MY_ENV=production" >> $GITHUB_ENV
        
      - name: Check Staging
        if: ${{ github.ref == 'refs/heads/staging' }}
        run: |
          echo "MY_ENV=staging" >> $GITHUB_ENV
      
      - name: Check Staging
        if: ${{ github.ref == 'refs/heads/development' }}
        run: |
          echo "MY_ENV=development" >> $GITHUB_ENV

  RunCode:
    name: Run Code
    runs-on: ubuntu-latest
    environment: ${{ env.GITHUB_ENV }}
    steps:
      - name: Print env var
        shell: bash
        run: |
          echo ${{ env.TEST_ENV_VAR }}
