name: Test Github Environments
on:
  push:

jobs:
  SetEnvironment:
    name: Set Environment
    runs-on: ubuntu-latest
    steps:
      - name: Check Prod
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_ENVIRONMENT: production
        run: |
          echo "RUNNING IN PROD"
        
      - name: Check Staging
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          GITHUB_ENVIRONMENT: staging
        run: |
          echo "RUNNING IN STAGING"
      
      - name: Check Staging
        if: ${{ github.ref == 'refs/heads/development' }}
        env:
          GITHUB_ENVIRONMENT: development
        run: |
          echo "RUNNING IN DEVELOPMENT"

  RunCode:
    name: Run Code
    runs-on: ubuntu-latest
    environment: ${{ env.GITHUB_ENVIRONMENT }}
    steps:
      - name: Print env var
        shell: bash
        run: |
          echo ${{ env.TEST_ENV_VAR }}
