name: Set Env Var

on:
  push:
    branches:
      - main
      - staging
      - development

jobs:
  set-env-var:
    runs-on: ubuntu-latest
    steps:
    - name: Set Environment Variable
      run: echo "ENVIRONMENT=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    - name: Print Environment Variable
      run: echo $ENVIRONMENT
      env:
        ENVIRONMENT: ${{ env.ENVIRONMENT }}