name: Deployment

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
    #   - staging

jobs:
  DeployCode:
    name: Deploy Code
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
    - name: Use variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
      env:
        REPOSITORY_VAR: ${{ vars.TEST_ENV_VAR }}
