name: Test Deployment

on:
  push:
    branches:
      - main
      - staging
      - development

jobs:
  SetEnvironment:
    name: SetEnvironment
    runs-on: ubuntu-latest
    steps:
    - name: Set Environment Variable
      run: echo "ENVIRONMENT=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    - name: Print Environment Variable
      run: echo $ENVIRONMENT
    outputs:
      workflow_environment: ${{ env.ENVIRONMENT }}

  RunCode:
    name: Run Code
    needs: SetEnvironment
    runs-on: ubuntu-latest
    #environment: ${{ needs.SetEnvironment.output.workflow_environment }}
    environment:
      name: "${GITHUB_REF#refs/heads/}"
    steps:
    - name: Use variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
      env:
        REPOSITORY_VAR: ${{ vars.TEST_ENV_VAR }}
